[package]
name = "eqx_window"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
cgmath = "0.18"
log = "0.4"
wgpu = "24.0"
pollster = "0.2"
eqx_app = { path = "../eqx_app", version = "0.1.0" }
